pipeline {
    agent any

    stages {
        stage('Execute Unit Tests'){
            parallel {
                stage('Unit Tests backend') {
                    agent {
                        docker {
                            image 'snakee/golang-junit:1.21'
                            reuseNode true
                        }
                    }
                    steps {
                        dir('bugtracker-backend') {
                            sh'''
                                go test -v ./... 2>&1 | go-junit-report > test-results.xml

                                # Generate code coverage report
                                go test -coverprofile=coverage.out -covermode=atomic ./...
                                go tool cover -html=coverage.out -o coverage.html

                                mkdir -p reports
                                mv coverage.html reports/
                            '''
                        }
                    }
                    environment {
                        HOME = "${WORKSPACE}"
                        GOCACHE = "${WORKSPACE}/.cache/go-build"
                        GOPATH = "${WORKSPACE}/.go"
                    }
                    post {
                        always {
                            junit 'bugtracker-backend/test-results.xml'
                            publishHTML target: [
                                reportName: 'Backend Code Coverage',
                                reportDir: 'bugtracker-backend/reports',
                                reportFiles: 'coverage.html'
                            ]
                        }
                    }
                }
                stage('Unit Tests frontend') {
                    agent {
                        docker {
                            image 'node:20-alpine'
                            reuseNode true
                        }
                    }
                    steps {
                        dir('bugtracker-frontend') {
                            sh '''
                            npm ci
                            npm test
                            mkdir -p reports
                            mv coverage reports/
                            '''
                        }
                    }
                    post {
                        always {
                            junit 'bugtracker-frontend/test-results.xml'
                            publishHTML target: [
                                reportName: 'Frontend Code Coverage',
                                reportDir: 'bugtracker-frontend/reports/coverage',
                                reportFiles: 'index.html'
                            ]
                        }
                    }
                }
            }
        }
        stage('Launch Application') {
            agent{
                docker {
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }
            steps {
                sh 'docker compose up --build -d'
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}

