pipeline {
    agent any

    stages {
        stage('Unit Tests frontent') {
            agent {
                docker {
                    image 'node:1420-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontent') {
                    sh '''
                      npm ci
                      npm test
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontent/test-results.xml'
                }
            }
        }
    }
}
